--!strict
--[=[
    Basic Purpose Utility library containing tons of utility packages
]=]

return {
	WeldConstraintUtils = require("@self/WeldConstraintUtils"),
	RemoteFunctionUtils = require("@self/RemoteFunctionUtils"),
	PreferredParentUtils = require("@self/PreferredParentUtils"),

	NetworkOwnerUtils = require("@self/NetworkOwnerUtils"),

	ParticleEmitterUtils = require("@self/ParticleEmitterUtils"),
	NumberRangeUtils = require("@self/NumberRangeUtils"),
	ExperienceUtils = require("@self/ExperienceUtils"),

	InputObjectUtils = require("@self/InputObjectUtils"),
	MultipleClickUtils = require("@self/MultipleClickUtils"),
	HapticFeedbackUtils = require("@self/HapticFeedbackUtils"),
	CoreGuiUtils = require("@self/CoreGuiUtils"),

	MathUtils = require("@self/MathUtils"),
	Vector3Utils = require("@self/Vector3Utils"),
	NearUtils = require("@self/NearUtils"),
	RandomUtils = require("@self/RandomUtils"),
	Color3Utils = require("@self/Color3Utils"),
	CFrameUtils = require("@self/CFrameUtils"),
	CFrameSerializationUtils = require("@self/CFrameSerializationUtils"),
	BezierUtils = require("@self/BezierUtils"),
	MemorizeUtils = require("@self/MemorizeUtils"),
	DefaultValueUtils = require("@self/DefaultValueUtils"),

	PlayerUtils = require("@self/PlayerUtils"),
	FriendUtils = require("@self/FriendUtils"),
	BadgeUtils = require("@self/BadgeUtils"),
	AnimationUtils = require("@self/AnimationUtils"),
	AttributeUtils = require("@self/AttributeUtils"),
	GroupUtils = require("@self/GroupUtils"),

	RbxThumbUtils = require("@self/RbxThumbUtils"),
	RbxAssetUtils = require("@self/RbxAssetUtils"),
	EnumUtils = require("@self/EnumUtils"),

	TextServiceUtils = require("@self/TextServiceUtils"),
	TextFilterUtils = require("@self/TextFilterUtils"),
	StringUtils = require("@self/StringUtils"),
	LipsumUtils = require("@self/LipsumUtils"),

	TeleportServiceUtils = require("@self/TeleportServiceUtils"),
	MarketplaceServiceUtils = require("@self/MarketplaceServiceUtils"),
	MemoryStoreUtils = require("@self/MemoryStoreUtils"),
	MessagingServiceUtils = require("@self/MessagingServiceUtils"),
}
